import React, {useEffect, useMemo, useState} from 'react';
import {createRoot} from 'react-dom/client';
import {ArrowRight, ArrowLeft, Award, CalendarPlus, Check, ChevronRight, CircleAlert, Clock3, DollarSign, Globe2, GraduationCap, Heart, Inbox, MapPin, Sparkles, Target, Trophy, Zap} from 'lucide-react';
import './styles.css';

const stages=['Старт','Профиль','Диагностика','Рекомендации','Сравнение','Roadmap','Следующий шаг'];
const initial={grade:'10 класс', age:'16', interests:['Computer Science'], gpa:'4.3', english:'B2', exam:'IELTS', score:'6.0', countries:['UK','Netherlands'], budget:12000, deadline:'2027', constraints:['Нужна стипендия'], completed:[]};
const programs=[
 {id:'bath',name:'University of Bath',country:'UK',city:'Bath',focus:'Computer Science',cost:18000,minScore:6.5,deadline:'15 Jan 2027',rank:'Top 10 UK',language:'English',fit:88,tag:'Сильный match'},
 {id:'twente',name:'University of Twente',country:'Netherlands',city:'Enschede',focus:'Technical Computer Science',cost:13500,minScore:6.0,deadline:'1 May 2027',rank:'Research-focused',language:'English',fit:91,tag:'Оптимальный бюджет'},
 {id:'groningen',name:'University of Groningen',country:'Netherlands',city:'Groningen',focus:'Computing Science',cost:14500,minScore:6.5,deadline:'15 Jan 2027',rank:'Top 100 Europe',language:'English',fit:82,tag:'Амбициозный'},
 {id:'manchester',name:'University of Manchester',country:'UK',city:'Manchester',focus:'Computer Science',cost:24000,minScore:6.5,deadline:'15 Jan 2027',rank:'Russell Group',language:'English',fit:65,tag:'Stretch'},
 {id:'leeds',name:'University of Leeds',country:'UK',city:'Leeds',focus:'Computer Science',cost:21500,minScore:6.0,deadline:'29 Jan 2027',rank:'Russell Group',language:'English',fit:76,tag:'Хороший match'},
 {id:'maastricht',name:'Maastricht University',country:'Netherlands',city:'Maastricht',focus:'Data Science & AI',cost:14500,minScore:6.5,deadline:'1 Apr 2027',rank:'Problem-based learning',language:'English',fit:79,tag:'Для AI-траектории'},
 {id:'nottingham',name:'University of Nottingham',country:'UK',city:'Nottingham',focus:'Computer Science',cost:22000,minScore:6.5,deadline:'15 Jan 2027',rank:'Global top 150',language:'English',fit:71,tag:'Сбалансированный'},
 {id:'utrecht',name:'Utrecht University',country:'Netherlands',city:'Utrecht',focus:'Information & Computing Sciences',cost:16000,minScore:6.5,deadline:'1 Apr 2027',rank:'Top 100 Europe',language:'English',fit:75,tag:'Амбициозный'},
 {id:'surrey',name:'University of Surrey',country:'UK',city:'Guildford',focus:'Computer Science',cost:19000,minScore:6.0,deadline:'15 Jan 2027',rank:'Industry links',language:'English',fit:83,tag:'Практичный выбор'},
 {id:'tilburg',name:'Tilburg University',country:'Netherlands',city:'Tilburg',focus:'Data Science',cost:12500,minScore:6.0,deadline:'1 May 2027',rank:'Business + tech',language:'English',fit:86,tag:'Бюджетный match'},
 {id:'bristol',name:'University of Bristol',country:'UK',city:'Bristol',focus:'Computer Science',cost:27000,minScore:7.0,deadline:'15 Jan 2027',rank:'Russell Group',language:'English',fit:55,tag:'High reach'},
 {id:'radboud',name:'Radboud University',country:'Netherlands',city:'Nijmegen',focus:'Computing Science',cost:14000,minScore:6.5,deadline:'1 Apr 2027',rank:'Research-focused',language:'English',fit:78,tag:'Сильный match'},
 {id:'lancaster',name:'Lancaster University',country:'UK',city:'Lancaster',focus:'Computer Science',cost:20500,minScore:6.5,deadline:'15 Jan 2027',rank:'Campus community',language:'English',fit:73,tag:'Сбалансированный'},
 {id:'vu',name:'Vrije Universiteit Amsterdam',country:'Netherlands',city:'Amsterdam',focus:'Computer Science',cost:15500,minScore:6.5,deadline:'1 Apr 2027',rank:'Tech ecosystem',language:'English',fit:81,tag:'Амбициозный'},
 {id:'exeter',name:'University of Exeter',country:'UK',city:'Exeter',focus:'Computer Science',cost:23500,minScore:6.5,deadline:'15 Jan 2027',rank:'Campus + career',language:'English',fit:68,tag:'Stretch'}
];
const scholarshipById={
 bath:{name:'Bath Global Leaders',coverage:'до £5k',deadline:'15 Jan 2027'},
 twente:{name:'University of Twente Scholarship',coverage:'€3k–€10k',deadline:'1 Feb 2027'},
 groningen:{name:'Eric Bleumink Fellowship',coverage:'tuition + living',deadline:'1 Dec 2026'},
 manchester:{name:'Global Futures Scholarship',coverage:'до £5k',deadline:'15 Jan 2027'},
 leeds:{name:'International Excellence',coverage:'до £5k',deadline:'29 Jan 2027'},
 maastricht:{name:'NL-High Potential',coverage:'tuition + living',deadline:'1 Feb 2027'},
 nottingham:{name:'Developing Solutions',coverage:'до 100%',deadline:'15 Jan 2027'},
 utrecht:{name:'Utrecht Excellence',coverage:'tuition',deadline:'1 Feb 2027'},
 surrey:{name:'International Excellence',coverage:'£5k',deadline:'15 Jan 2027'},
 tilburg:{name:'Tilburg Scholarship',coverage:'€5k',deadline:'1 Feb 2027'},
 bristol:{name:'Think Big',coverage:'£5k–£20k',deadline:'24 Feb 2027'},
 radboud:{name:'Radboud Scholarship',coverage:'€15k',deadline:'1 Mar 2027'},
 lancaster:{name:'Global Scholarship',coverage:'£2k',deadline:'15 Jan 2027'},
 vu:{name:'VU Fellowship',coverage:'tuition + allowance',deadline:'1 Feb 2027'},
 exeter:{name:'Global Excellence',coverage:'до £7.5k',deadline:'15 Jan 2027'}
};
programs.forEach(program=>{program.scholarship=scholarshipById[program.id]||null});
const money=n=>`$${n.toLocaleString('en-US')}`;
function readStoredProfile(){try{const stored=localStorage.getItem('ns-profile');if(!stored)return initial;const parsed=JSON.parse(stored);if(!parsed||typeof parsed!=='object')return initial;return {...initial,...parsed,interests:Array.isArray(parsed.interests)?parsed.interests:initial.interests,countries:Array.isArray(parsed.countries)?parsed.countries:initial.countries,constraints:Array.isArray(parsed.constraints)?parsed.constraints:initial.constraints,completed:Array.isArray(parsed.completed)?parsed.completed:initial.completed}}catch{return initial}}
function readStoredStage(){try{const stored=Number(localStorage.getItem('ns-stage'));return Number.isInteger(stored)&&stored>=0&&stored<=6?stored:0}catch{return 0}}
function calendarDate(dateLike){const date=dateLike instanceof Date?new Date(dateLike):new Date(dateLike);if(Number.isNaN(date.getTime()))return null;date.setHours(9,0,0,0);return date}
function downloadCalendarEvent({title,description,start}){const date=calendarDate(start);if(!date)return;const end=new Date(date);end.setHours(end.getHours()+1);const format=d=>d.toISOString().replace(/[-:]/g,'').replace(/\.\d{3}Z$/,'Z');const ics=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//Northstar//Admissions//EN','BEGIN:VEVENT',`UID:northstar-${Date.now()}@app`,`DTSTAMP:${format(new Date())}`,`DTSTART:${format(date)}`,`DTEND:${format(end)}`,`SUMMARY:${title}`,`DESCRIPTION:${description}`,'END:VEVENT','END:VCALENDAR'].join('\r\n');const blob=new Blob([ics],{type:'text/calendar;charset=utf-8'});const url=URL.createObjectURL(blob);const link=document.createElement('a');link.href=url;link.download=`northstar-${title.toLowerCase().replace(/[^a-z0-9]+/gi,'-')}.ics`;document.body.appendChild(link);link.click();link.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function addDays(days){const date=new Date();date.setDate(date.getDate()+days);return date}
function getRecommendations(p){return programs.filter(x=>p.countries.includes(x.country)).map(x=>({...x,fit:Math.max(35,Math.min(96,x.fit+(p.budget>=x.cost?8:-16)+(Number(p.score)>=x.minScore?6:-11)+(p.interests.includes('AI / Data')&&x.focus.includes('Data')?8:0)))})).sort((a,b)=>b.fit-a.fit).slice(0,4)}
function diagnosis(p){let d=[]; d.push(`Ты уже сузил выбор до ${p.countries.join(' и ')} — это помогает сравнивать требования, а не тонуть в десятках стран.`); if(Number(p.score)>=6.5)d.push(`IELTS ${p.score} закрывает базовый языковой порог для большинства найденных программ.`);else d.push(`IELTS ${p.score} — рабочая отправная точка, но для более конкурентных программ стоит целиться в 6.5–7.0.`); d.push(`Твой бюджет около ${money(p.budget)} в год делает важными Нидерланды и варианты со стипендией.`); if(p.constraints.includes('Нужна стипендия'))d.push('Финансирование — главный фильтр: в следующих шагах ищем scholarship и проверяем реальные дедлайны отдельно.'); d.push(`Цель на ${p.deadline}: подготовить профиль заранее, потому что часть дедлайнов закрывается уже в январе.`); return d}
function roadmap(p){return [
 {date:'Сентябрь–октябрь 2026',title:`Поднять ${p.exam} до ${Number(p.score)<6.5?'6.5+':'7.0+'}`,desc:'Диагностический тест, недельный план и один пробный экзамен.'},
 {date:'Ноябрь 2026',title:'Собрать academic profile',desc:'Табель, перевод оценок, список проектов и олимпиад в одном файле.'},
 {date:'Декабрь 2026',title:'Выбрать 3–5 приоритетных программ',desc:'Сравнить стоимость, требования к предметам и доступные scholarships.'},
 {date:'Январь 2027',title:'Подать первые заявки',desc:'Проверить дедлайн каждой программы и попросить рекомендации заранее.'},
 {date:'Февраль–апрель 2027',title:'Эссе и финансирование',desc:'Адаптировать мотивационное письмо, отправить заявки на гранты и scholarships.'}
]}
function App(){
 const [stage,setStage]=useState(readStoredStage());
 const [p,setP]=useState(readStoredProfile);
 const [selected,setSelected]=useState([]);
 const [loading,setLoading]=useState(false);
 const recs=useMemo(()=>getRecommendations(p),[p]);
 const [step,setStep]=useState(0);
 useEffect(()=>{localStorage.setItem('ns-stage',stage);localStorage.setItem('ns-profile',JSON.stringify(p))},[stage,p]);
 const update=(k,v)=>setP(x=>({...x,[k]:v}));
 const next=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setStage(Math.min(6,stage+1));setStep(0)},350)};
 return <div className="min-h-screen bg-[#f8f6f1] text-[#172521]"><header className="border-b border-[#dedbd2] bg-[#fbfaf7]/90 backdrop-blur sticky top-0 z-30"><div className="max-w-6xl mx-auto px-5 py-4 flex items-center justify-between"><button type="button" onClick={()=>setStage(0)} aria-label="Вернуться на старт" className="flex items-center gap-2"><span className="logo-mark">✦</span><span className="font-extrabold tracking-tight">northstar</span></button><div className="hidden md:flex items-center gap-1 text-xs font-bold text-[#6f776f]">{stages.map((s,i)=><React.Fragment key={s}><button type="button" disabled={i>stage} aria-label={'Перейти к этапу '+(i+1)+': '+s} onClick={()=>i<=stage&&setStage(i)} className={'stage-button '+(i===stage?'text-[#172521]':'')}>{i<stage?'✓ ':''}{s}</button>{i<6&&<ChevronRight size={13} aria-hidden="true"/>}</React.Fragment>)}</div><span className="text-xs text-[#6f776f]">{stage}/6 завершено</span></div><div className="mobile-progress max-w-6xl mx-auto px-5 pb-3" aria-label={'Прогресс: шаг '+stage+' из 6'}><div className="mobile-progress-bar" role="progressbar" aria-valuemin="0" aria-valuemax="6" aria-valuenow={stage}><span style={{width:(stage/6)*100+'%'}} /></div><div className="mobile-progress-label">Шаг {stage} из 6 — {stages[stage]}</div></div></header><main className="max-w-6xl mx-auto px-5 py-8 md:py-12">{stage===0&&<Landing onStart={()=>setStage(1)}/>} {stage===1&&<Profile p={p} update={update} step={step} setStep={setStep} next={next}/>} {stage===2&&<Diagnosis p={p} next={next}/>} {stage===3&&<Recommendations p={p} recs={recs} next={next} selected={selected} setSelected={setSelected} setStage={setStage}/>} {stage===4&&<Compare recs={recs} selected={selected} next={next}/>} {stage===5&&<Roadmap p={p} recs={recs} next={next}/>} {stage===6&&<NextStep p={p} setP={setP} recs={recs}/>} {loading&&<div className="fixed inset-0 bg-[#172521]/10 backdrop-blur-sm flex items-center justify-center z-40"><div className="panel p-6 flex items-center gap-3"><Sparkles className="text-[#e76443] animate-pulse twinkle" aria-hidden="true"/>Персонализируем маршрут…</div></div>}</main><footer className="max-w-6xl mx-auto px-5 pb-8 text-xs text-[#8b918c] flex justify-between"><span>Northstar · демо для хакатона</span><span>Все данные о вузах — демонстрационные</span></footer></div>}
function Landing({onStart}){return <section className="grid md:grid-cols-[1.1fr_.9fr] gap-10 items-center min-h-[72vh]"><div><div className="eyebrow"><span className="dot"/>для учеников 10–11 класса из Казахстана</div><h1 className="display text-6xl md:text-8xl leading-[.92] mt-6">Твой следующий шаг уже <em>виден.</em></h1><p className="text-lg text-[#5d6860] max-w-xl mt-7 leading-relaxed">Northstar превращает выбор CS-бакалавриата в UK или Нидерландах в понятный маршрут — от твоих оценок и бюджета до конкретного плана на 90 дней.</p><button onClick={onStart} className="btn-primary mt-8">Собрать мой маршрут <ArrowRight size={18}/></button><div className="flex gap-6 mt-8 text-sm text-[#687169]"><span><Check size={15} className="inline text-[#5c8b66]"/> 3–5 объяснённых вариантов</span><span><Check size={15} className="inline text-[#5c8b66]"/> roadmap по датам</span></div></div><div className="hero-card"><div className="absolute -top-4 -right-4 badge bg-[#e9a857] text-[#172521]">не каталог — компас</div><div className="compass">✦</div><div className="mt-8"><div className="text-xs uppercase tracking-[.2em] text-[#c7d8c3]">на выходе</div><h3 className="display text-4xl text-white mt-2">3 понятных<br/>варианта</h3><p className="text-[#c7d8c3] mt-3">с причинами, сравнением<br/>и ближайшим действием</p></div><div className="route-line"/><div className="flex justify-between text-xs text-[#c7d8c3]"><span>профиль</span><span>решение</span><span>действие</span></div></div></section>}
function Profile({p,update,step,setStep,next}){
 const steps=['Контекст','Интересы','Профиль','Язык','План'];
 const ageValue=Number(p.age);
 const ageValid=String(p.age).trim()!==''&&Number.isInteger(ageValue)&&ageValue>=13&&ageValue<=19;
 const gpaValue=Number(p.gpa);
 const gpaValid=String(p.gpa).trim()!==''&&Number.isFinite(gpaValue)&&gpaValue>=0&&gpaValue<=5;
 const can=step===0?!!p.grade&&ageValid:step===1?p.interests.length>0:step===2?gpaValid:step===3?!!p.score:!!p.budget;
 return <section className="max-w-3xl mx-auto">
  <div className="eyebrow"><span className="dot"/>шаг 1 из 6 · твой контекст</div>
  <h2 className="display text-5xl mt-4">Сначала — ты.</h2>
  <p className="muted mt-3">Пять коротких шагов. Northstar сохранит прогресс автоматически.</p>
  <div className="flex gap-2 mt-8 overflow-x-auto pb-2">{steps.map((x,i)=><button type="button" key={x} onClick={()=>setStep(i)} aria-label={'Открыть раздел анкеты: '+x} className={'step-pill '+(i===step?'active':'')}>{i+1}. {x}</button>)}</div>
  <div className="panel mt-4 p-6 md:p-9">
   {step===0&&<><Field label="В каком ты сейчас классе?"><select value={p.grade} onChange={e=>update('grade',e.target.value)}><option>9 класс</option><option>10 класс</option><option>11 класс</option></select></Field><Field label="Возраст"><input type="number" min="13" max="19" value={p.age} onChange={e=>update('age',e.target.value)} aria-invalid={!ageValid}/>{!ageValid&&<p className="error mt-2">Укажи целое число от 13 до 19.</p>}</Field></>}
   {step===1&&<><Field label="Что хочется изучать?"><div className="grid sm:grid-cols-2 gap-3">{['Computer Science','AI / Data','Engineering','Product design'].map(x=><button type="button" key={x} onClick={()=>update('interests',p.interests.includes(x)?p.interests.filter(i=>i!==x):[...p.interests,x])} className={'choice '+(p.interests.includes(x)?'chosen':'')} aria-pressed={p.interests.includes(x)}>{p.interests.includes(x)&&<Check size={16} aria-hidden="true"/>} {x}</button>)}</div></Field></>}
   {step===2&&<><Field label="Средняя оценка / GPA"><input type="number" min="0" max="5" step="0.1" value={p.gpa} onChange={e=>update('gpa',e.target.value)} placeholder="например, 4.3" aria-invalid={!gpaValid}/><p className="hint mt-2"><CircleAlert size={15} aria-hidden="true"/> Ожидается средняя оценка по шкале 0–5: например, 4.3. Это не точная конверсия в GPA.</p>{!gpaValid&&<p className="error mt-2">Введи число от 0 до 5.</p>}</Field></>}
   {step===3&&<><Field label="Язык и экзамен"><div className="grid sm:grid-cols-2 gap-3"><select value={p.exam} onChange={e=>update('exam',e.target.value)}><option>IELTS</option><option>TOEFL</option><option>ЕНТ</option></select><input value={p.score} onChange={e=>update('score',e.target.value)} placeholder="балл"/></div></Field></>}
   {step===4&&<><Field label="Куда подаёмся?"><div className="flex gap-3">{['UK','Netherlands'].map(x=><button type="button" key={x} onClick={()=>update('countries',p.countries.includes(x)?p.countries.filter(i=>i!==x):[...p.countries,x])} className={'choice '+(p.countries.includes(x)?'chosen':'')} aria-pressed={p.countries.includes(x)}>{p.countries.includes(x)&&<Check size={16} aria-hidden="true"/>} {x}</button>)}</div></Field><Field label={'Год поступления: '+p.deadline}><select value={p.deadline} onChange={e=>update('deadline',e.target.value)}><option>2027</option><option>2028</option></select></Field><Field label={'Бюджет на обучение в год: '+money(p.budget)}><input type="range" min="6000" max="30000" step="1000" value={p.budget} onChange={e=>update('budget',Number(e.target.value))} aria-label="Годовой бюджет на обучение"/><div className="flex justify-between text-xs text-[#889189] mt-2"><span>$6k</span><span>$30k</span></div></Field><Field label="Ограничение"><button type="button" onClick={()=>update('constraints',p.constraints.includes('Нужна стипендия')?[]:['Нужна стипендия'])} className={'choice '+(p.constraints.length?'chosen':'')} aria-pressed={p.constraints.length>0}><Heart size={16} aria-hidden="true"/>Нужна стипендия / помощь с финансированием</button></Field></>}
   {!can&&step!==0&&<p className="error mt-4">Заполни этот пункт, чтобы продолжить.</p>}
   <div className="flex justify-between mt-9"><button type="button" disabled={step===0} onClick={()=>setStep(step-1)} className="btn-ghost"><ArrowLeft size={16} aria-hidden="true"/> Назад</button>{step<4?<button type="button" disabled={!can} onClick={()=>setStep(step+1)} className="btn-primary">Дальше <ArrowRight size={16} aria-hidden="true"/></button>:<button type="button" disabled={!can} onClick={next} className="btn-primary">Собрать диагностику <Sparkles size={16} aria-hidden="true"/></button>}</div>
  </div>
 </section>
}
function Field({label,children}){return <label className="block mt-6"><span className="label">{label}</span><div className="mt-2">{children}</div></label>}
function Diagnosis({p,next}){return <section className="max-w-4xl mx-auto"><Top icon={<Target/>} kicker="шаг 2 из 6" title="Вот как выглядит твоя точка старта." sub="Не оценка личности — рабочая гипотеза, которую можно проверить действиями."/><div className="grid md:grid-cols-[1fr_.8fr] gap-5 mt-8"><div className="panel p-7"><div className="eyebrow">диагностика northstar</div><div className="space-y-5 mt-6">{diagnosis(p).map((x,i)=><div className="flex gap-3" key={x}><span className="number">0{i+1}</span><p className="leading-relaxed">{x}</p></div>)}</div></div><div className="dark-panel p-7"><div className="text-xs uppercase tracking-[.2em] text-[#a8c1a5]">профиль собран</div><div className="mt-6 space-y-4 text-sm"><Stat index={0} icon={<GraduationCap/>} a={p.interests.join(' · ')} b="фокус"/><Stat index={1} icon={<Globe2/>} a={p.countries.join(' + ')} b="направление"/><Stat index={2} icon={<DollarSign/>} a={money(p.budget)} b="годовой бюджет"/></div></div></div><button type="button" onClick={next} className="btn-primary mt-7">Показать мои варианты <ArrowRight size={17} aria-hidden="true"/></button></section>}
function Top({icon,kicker,title,sub}){return <div><div className="eyebrow">{icon}<span>{kicker}</span></div><h2 className="display text-5xl mt-4">{title}</h2><p className="muted mt-3">{sub}</p></div>}
function Stat({icon,a,b,index=0}){return <div className="stat-row flex items-center gap-3" style={{'--delay':(index*80)+'ms'}}><span className="icon-box">{icon}</span><div><div className="font-bold">{a}</div><div className="text-[#a8c1a5] text-xs">{b}</div></div></div>}
function Recommendations({p,recs,next,selected,setSelected,setStage}){return <section><Top icon={<Sparkles/>} kicker="шаг 3 из 6 · персональный shortlist" title="Не просто список. Вот почему." sub="Результаты пересчитываются от бюджета, стран и экзамена. Нажми на карточки, чтобы добавить их в сравнение."/><div className="flex items-center gap-2 mt-7 text-sm text-[#69756d]"><Zap size={16} className="text-[#e76443]" aria-hidden="true"/> Демо реактивности: поменяй бюджет в профиле — и Northstar изменит shortlist.</div>{recs.length===0?<div className="empty-state panel mt-5 p-8 md:p-12 text-center"><Inbox size={42} className="mx-auto text-[#e76443]" aria-hidden="true"/><h3 className="display text-3xl mt-5">Пока нет программ под эти параметры.</h3><p className="muted max-w-md mx-auto mt-3">Расширь страны или увеличь бюджет в профиле — Northstar попробует собрать новый shortlist.</p><button type="button" onClick={()=>setStage(1)} className="btn-primary mt-6">Вернуться к профилю <ArrowLeft size={16} aria-hidden="true"/></button></div>:<><div className="grid md:grid-cols-2 gap-5 mt-5">{recs.slice(0,4).map(x=><ProgramCard key={x.id} x={x} p={p} selected={selected.includes(x.id)} toggle={()=>setSelected(selected.includes(x.id)?selected.filter(y=>y!==x.id):[...selected,x.id])}/>)}</div><div className="flex justify-between items-center mt-7"><span className="source">ⓘ Стоимость, дедлайны, требования и scholarships — демонстрационные данные для прототипа.</span><button type="button" onClick={next} className="btn-primary">К сравнению <ArrowRight size={17} aria-hidden="true"/></button></div></>}</section>}
function ProgramCard({x,p,selected,toggle}){return <button type="button" onClick={toggle} aria-pressed={selected} className={'program-card text-left '+(selected?'selected':'')}><div className="flex justify-between gap-3"><div><div className="text-xs text-[#718078] flex items-center gap-1"><MapPin size={13} aria-hidden="true"/>{x.city}, {x.country}</div><h3 className="font-extrabold text-xl mt-2">{x.name}</h3><p className="text-sm text-[#627067] mt-1">{x.focus}</p></div><span className="fit">{x.fit}%<small>оценочно</small></span></div><div className="mt-5 space-y-2 text-sm"><div className="reason"><Check size={15} aria-hidden="true"/><span>Бюджет: твои {money(p.budget)}<small className="demo-inline">демо</small> {p.budget>=x.cost?'покрывают':'ниже'} ориентир {money(x.cost)}<small className="demo-inline">демо</small>.</span></div><div className="reason"><Check size={15} aria-hidden="true"/><span>{p.exam} {p.score}: {Number(p.score)>=x.minScore?'соответствует':'нужно подтянуть до'} {x.minScore}<small className="demo-inline">демо</small>.</span></div><div className="reason"><Check size={15} aria-hidden="true"/><span>{x.tag} · дедлайн {x.deadline}<small className="demo-inline">демо</small></span></div></div>{x.scholarship&&<div className="scholarship-badge"><Award size={16} aria-hidden="true"/><span>{x.scholarship.name} · {x.scholarship.coverage}<small>демо-данные · дедлайн {x.scholarship.deadline}</small></span></div>}<div className="card-footer"><span>{x.rank}</span><span>{selected?'✓ В сравнении':'Добавить в сравнение'}</span></div></button>}
function Compare({recs,selected,next}){let xs=recs.filter(x=>selected.includes(x.id));if(xs.length<2)xs=recs.slice(0,2);return <section><Top icon={<Trophy/>} kicker="шаг 4 из 6 · decision view" title="Увидеть разницу бок о бок." sub="Мы оставили только параметры, которые влияют на твоё решение: деньги, язык, требования и время."/><div className="overflow-x-auto panel mt-8"><table className="w-full text-left min-w-[680px]"><thead><tr><th>Параметр</th>{xs.map(x=><th key={x.id}>{x.name}</th>)}</tr></thead><tbody><tr><td className="font-bold text-[#66736a]">Страна</td>{xs.map(x=><td key={x.id}>{x.country}</td>)}</tr><tr><td className="font-bold text-[#66736a]">Стоимость / год</td>{xs.map(x=><td key={x.id}>{money(x.cost)}<small className="demo-inline">демо</small></td>)}</tr><tr><td className="font-bold text-[#66736a]">IELTS минимум</td>{xs.map(x=><td key={x.id}>{x.minScore}<small className="demo-inline">демо</small></td>)}</tr><tr><td className="font-bold text-[#66736a]">Дедлайн</td>{xs.map(x=><td key={x.id}><div>{x.deadline}<small className="demo-inline">демо</small></div><button type="button" className="btn-ghost calendar-table-button" onClick={()=>downloadCalendarEvent({title:'Дедлайн — '+x.name,description:'Проверь требования и заявку в Northstar. Демонстрационная дата: '+x.deadline+'.',start:x.deadline})}><CalendarPlus size={14} aria-hidden="true"/>Добавить в календарь</button></td>)}</tr><tr><td className="font-bold text-[#66736a]">Язык</td>{xs.map(x=><td key={x.id}>{x.language}</td>)}</tr><tr><td className="font-bold text-[#66736a]">Стипендия</td>{xs.map(x=><td key={x.id}>{x.scholarship?<><strong>{x.scholarship.name}</strong><small className="demo">{x.scholarship.coverage} · демо · до {x.scholarship.deadline}</small></>:<span className="muted">Не найдена <small className="demo">демо</small></span>}</td>)}</tr><tr><td className="font-bold text-[#66736a]">Оценка fit</td>{xs.map(x=><td key={x.id}>{x.fit}%<small className="demo-inline">оценочно</small></td>)}</tr></tbody></table></div><p className="source mt-4">ⓘ В реальном продукте эти поля синхронизируются с официальными страницами вузов перед подачей. Кнопка календаря создаёт локальный .ics-файл.</p><button type="button" onClick={next} className="btn-primary mt-7">Построить Roadmap <ArrowRight size={17} aria-hidden="true"/></button></section>}
function Roadmap({p,recs,next}){const items=roadmap(p);return <section className="max-w-4xl mx-auto"><Top icon={<Clock3/>} kicker="шаг 5 из 6 · твой календарь" title="План без паники в последний месяц." sub={'Траектория под '+p.deadline+': сначала язык и документы, потом заявки и финансирование.'}/><div className="timeline mt-9">{items.map((x,i)=><div className="timeline-item" key={x.date}><div className="timeline-dot">{i+1}</div><div><div className="text-xs font-bold uppercase tracking-wider text-[#e76443]">{x.date}</div><h3 className="font-extrabold text-xl mt-1">{x.title}</h3><p className="muted mt-1">{x.desc}</p></div></div>)}</div><div className="panel p-5 mt-2"><div className="flex items-center gap-2 font-extrabold"><CalendarPlus size={17} className="text-[#e76443]" aria-hidden="true"/>Дедлайны из твоего shortlist</div><p className="source mt-2">Добавь ориентировочную дату в календарь; перед подачей проверь официальный сайт.</p><div className="calendar-list mt-4">{recs.slice(0,3).map(x=><div className="calendar-item" key={x.id}><div><strong>{x.name}</strong><div className="muted text-sm">{x.deadline}<small className="demo-inline">демо</small></div></div><button type="button" className="btn-ghost" onClick={()=>downloadCalendarEvent({title:'Дедлайн — '+x.name,description:'Демонстрационный дедлайн программы Northstar: '+x.deadline+'.',start:x.deadline})}><CalendarPlus size={14} aria-hidden="true"/>Добавить дедлайн в календарь</button></div>)}</div></div><div className="notice mt-8"><CircleAlert size={18} aria-hidden="true"/><span>Даты ориентировочные: перед подачей проверь официальную страницу каждой программы.</span></div><button type="button" onClick={next} className="btn-primary mt-7">Забрать ближайший шаг <ArrowRight size={17} aria-hidden="true"/></button></section>}
function NextStep({p,setP,recs}){const options=['Записаться на пробный '+p.exam,'Собрать оценки и проекты в один файл','Открыть страницы двух shortlisted вузов'];const toggle=x=>setP(a=>({...a,completed:a.completed.includes(x)?a.completed.filter(y=>y!==x):[...a.completed,x]}));return <section className="max-w-4xl mx-auto"><Top icon={<Target/>} kicker="шаг 6 из 6 · action" title="Один шаг сегодня. Большой выбор — позже." sub="Northstar сохранил маршрут. Начни с действия, которое двигает заявку вперёд."/><div className="grid md:grid-cols-[1.1fr_.9fr] gap-5 mt-8"><div className="next-card"><div className="badge bg-[#e9a857] text-[#172521]">Ближайший шаг</div><h3 className="display text-4xl mt-5">Пройди пробный {p.exam} в ближайшие 7 дней.</h3><p className="text-[#c7d8c3] mt-4">Цель: понять разрыв до нужного балла, а не ждать идеального момента.</p><button type="button" onClick={()=>downloadCalendarEvent({title:'Пробный '+p.exam,description:'Northstar: пройти пробный '+p.exam+' в ближайшие 7 дней.',start:addDays(7)})} className="btn-light mt-7" aria-label={'Добавить пробный '+p.exam+' в календарь'}>Отметить в календаре <CalendarPlus size={16} aria-hidden="true"/></button></div><div className="panel p-7"><div className="eyebrow">прогресс сохраняется</div><div className="space-y-4 mt-6">{options.map(x=><label key={x} className="check-row"><input type="checkbox" aria-label={x} checked={p.completed.includes(x)} onChange={()=>toggle(x)}/><span>{x}</span></label>)}</div><div className="mt-8 pt-5 border-t border-[#e1dfd7] text-sm text-[#69756d]">{p.completed.length}/{options.length} выполнено · shortlist: {recs.length} программы</div></div></div><button type="button" onClick={()=>{setP(initial);localStorage.removeItem('ns-stage');localStorage.removeItem('ns-profile');location.reload()}} className="btn-ghost mt-8" aria-label="Сбросить сохранённое состояние и начать заново">Начать заново</button></section>}
class ErrorBoundary extends React.Component{constructor(props){super(props);this.state={hasError:false}}static getDerivedStateFromError(){return {hasError:true}}handleReset=()=>{localStorage.removeItem('ns-stage');localStorage.removeItem('ns-profile');window.location.reload()};render(){if(this.state.hasError)return <div className="min-h-screen bg-[#f8f6f1] flex items-center justify-center p-6"><div className="panel p-8 max-w-md text-center"><CircleAlert size={42} className="mx-auto text-[#e76443]" aria-hidden="true"/><h1 className="display text-4xl mt-5">Что-то пошло не так.</h1><p className="muted mt-3">Сбрось локальное состояние и попробуй пройти маршрут ещё раз.</p><button type="button" onClick={this.handleReset} className="btn-primary mt-6" aria-label="Сбросить состояние приложения">Сбросить состояние</button></div></div>;return this.props.children}}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
